liberated:
  auth:
    google:
      mock: false
      client-id: ${GOOGLE_CLIENT_ID}
    apple:
      mock: false
    otp:
      mock: false
  jwt:
    secret: ${LIBERATED_JWT_SECRET}

spring:
  h2:
    console:
      enabled: false
